[workspace]
resolver = "2"

members = [
    "core/schiebung-core-rs",
    "core/schiebung-core-py",
    "comms",
    "visualizer/schiebung-rerun-rs",
    "visualizer/schiebung-rerun-py",
    "server/schiebung-server-rs",
    "server/schiebung-server-py",
]
